Translation in pa-IN.
CyBear-Jinni/cbj_app pull request #486
Opened 2022-10-04 18:13 UTC by Sahilbal

2022-10-04 18:31 UTC, guyluz11 requested changes

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "Room:_": " ਕਮਰਾ: {}",
Extra space please delete it

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "Name:_": "ਨਾਮ  : {}",
Extra space before the `:` please delete it

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "Lamps_Page": "ਦੀਵਾ  ਪੰਨਾ ",
2 spaces between the worlds, please keep one.
And one extra space in the end.

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "Blinds_Page": " ਪਰਦਾ ਪੰਨਾ",
Extra space please delete it

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "Device_type:_": "ਡਿਵਾਈਸ ਦੀ ਕਿਸਮ : {}",
Extra space before `:` please delete it

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "Device_name:": "ਡਿਵਾਈਸ ਦਾ ਨਾਮ :",
Extra space before ":" please delete it

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "WiFi_Name": "ਵਾਈਫਾਈ  ਨਾਮ",
You have double space

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "WiFi_password_is_required": "ਵਾਈਫਾਈ  ਪਾਸਵਰਡ ਦੀ ਲੋੜ ਹੈ",
You have double space

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "WiFi_Password": "ਵਾਈਫਾਈ  ਪਾਸਵਰਡ",
You have double space

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "_Boilers": "{}ਬਾਇਲਰ ",
Space is needed after `}`

2022-10-04 18:31 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "Waiting_for_user_to_get_connected_to_WiFi": "ਉਪਭੋਗਤਾ ਦੇ  ਵਾਈਫਾਈ  ਨਾਲ ਕਨੈਕਟ ਹੋਣ ਦੀ ਉਡੀਕ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ",
2 double spaces please fix.

2022-10-04 18:54 UTC, guyluz11 requested changes
I think this is the only one needed now

2022-10-04 18:54 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "_Boilers": "{} ਬਾਇਲਰ ",
Extra space in the end

2022-10-04 18:55 UTC, Sahilbal commented on assets/translations/pa-IN.json
> +  "Device_type:_": "ਡਿਵਾਈਸ ਦੀ ਕਿਸਮ : {}",
okay got it!. thank you.

2022-10-04 19:19 UTC, Sahilbal commented
I think I have made all the required changes . So please accept my pull request and give it hactoberfest accepted tag. kindly let me know if I am still lagging to meet your requirements.  I shall be very thankful to you. Also you are a best teacher I ever met because our teachers don't guide us  like you. They get annoyed very often when we ask them the same thing second time.

2022-10-04 19:28 UTC, guyluz11 requested changes

2022-10-04 19:28 UTC, guyluz11 commented on assets/translations/pa-IN.json
> +  "Lamps_Page": "ਦੀਵਾ ਪੰਨਾ ",
Extra space in the end

2022-10-05 05:39 UTC, Sahilbal commented
I have made all the required changes. So please accept my pull request and give it hactoberfest accepted tag.

2022-10-05 08:01 UTC, guyluz11 approved these changes
Nice 👍

2022-10-05 08:03 UTC, merged

2022-10-05 08:04 UTC, guyluz11 commented
Thanks for the pr @Sahilbal and happy Hacktoberfest 😁

2022-10-05 08:29 UTC, Sahilbal commented
> Thanks for the pr @Sahilbal and happy Hacktoberfest 😁

thank you!