Upgraded all the packages to latest version.
CyBear-Jinni/cbj_app pull request #676
Opened 2023-10-05 13:21 UTC by radar101

2023-10-05 14:32 UTC, guyluz11 requested changes

2023-10-05 14:32 UTC, guyluz11 commented on android/app/src/main/AndroidManifest.xml
>                   Flutter's first frame. -->
Why have you deleted this file?.
Also this comment it part of the line that you deleted, it should get removed with it

2023-10-05 14:32 UTC, guyluz11 commented on lib/injection.dart
> +GetIt getIt = GetIt.instance;
Can it be `final GetIt`?

2023-10-05 14:32 UTC, guyluz11 commented on pubspec.yaml
> +
Remove extra space

2023-10-05 14:32 UTC, guyluz11 commented on pubspec.yaml
> +
Remove extra space

2023-10-05 14:32 UTC, guyluz11 commented on pubspec.yaml
> +  injectable_generator: ^2.1.3 # Version 2
`injectable_generator` already exists in `dev_dependencies`.
Please update the version there

2023-10-05 16:15 UTC, radar101 reviewed
Made the required changes. Please review them.

2023-10-06 09:00 UTC, guyluz11 commented on pubspec.yaml
> +  injectable_generator: ^2.1.3 # Version 2
You removed it entirely instead of updating it.
Please update the existing one

2023-10-06 12:41 UTC, radar101 commented
I've deleted it because the updated package was mentioned in dev_dependendies as
injectable_generator: ^2.1.5

2023-10-12 17:07 UTC, guyluz11 commented
Thanks for creating the pr

I have decided to take this pr https://github.com/CyBear-Jinni/cbj_app/pull/679 because it included update for all of the packages.

2023-10-12 17:07 UTC, closed without merging